### ISSUE TITLE
Kick command kicks the admin

### ISSUE THREAD

**Issue by Shurugaz** [MeLlamoPablo/schedulebot#9] opened 2017-01-10 20:35 UTC
Kick command kicks the admin, not the player mentioned

**Comment by MeLlamoPablo** [comment] 2017-01-10 20:50
Thanks for reporting. Both are caused by lazy testing on my side, so I apologize. I'll get on it asap.

**Comment by Shurugaz** [comment] 2017-01-10 20:56
No problem at all, we all know it's still a work in progress :)

**Comment by MeLlamoPablo** [comment] 2017-01-11 10:56
Fixed in version 1.1.1. You may update your bot by following the instructions [here](https://github.com/MeLlamoPablo/schedulebot/tree/dota#updating).

**Closed by MeLlamoPablo** 2017-01-11 10:56 UTC
